version: '@version@'
name: BaiTeam
main: sky_bai.bukkit.baiteam.BaiTeam
api-version: 1.13
depend: 
- DungeonsXL
- ProtocolLib
- PlaceholderAPI
authors: 
- sky_bai


commands: 
  BaiTeam: 
  BaiTeamCmd: 